[package]
name = "ruxfuse"
version = "0.1.0"
edition = "2021"
authors = ["Harris <zhengyuanhao@pku.edu.cn>"]
description = "RuxOS fuse module"
license = "Mulan PSL v2"
homepage = "https://github.com/syswonder/ruxos"
repository = "https://github.com/syswonder/ruxos/tree/main/modules/ruxfuse"

[features]
default = []

[dependencies]
log = "0.4"
spin = "0.9"
axfs_vfs = { path = "../../crates/axfs_vfs"}

